server:
  port: 8888

twba:
  aws:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${SECRET_ACCESS_KEY}
  kinesis:
    stream-name-prefix: ${STREAM_PREFIX}
    aws-region: ${AWS_REGION}